port: 7880
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 52000 # Production should be 60000
  use_ice_lite: true
keys:
  devkey: secret
webhook:
  api_key: devkey
  urls:
    - http://signaling:8080/webhooks/livekit